export const values = [
  { id: 1, label: '受容', description: 'ありのままの自分を受け入れてもらう' },
  { id: 2, label: '正確', description: '自分の意見や信念を正しく伝える' },
  { id: 3, label: '達成', description: 'なにか重要なことを達成する' },
  { id: 4, label: '冒険', description: '新しくてワクワクする体験をする' },
  { id: 5, label: '魅力', description: '身体的な魅力を保つ' },
  { id: 6, label: '権威', description: '他者に対して責任を持って指導する' },
  { id: 7, label: '自治', description: '人まかせにしないで自分で決める' },
  { id: 8, label: '美的', description: '身のまわりの美しいものを味わう' },
  { id: 9, label: '庇護', description: '他者のめんどうをみる' },
  { id: 10, label: '挑戦', description: '難しい仕事や問題に取り組む' },
  {
    id: 11,
    label: '変化',
    description: '変化に富んだバラエティ豊かな人生を送る',
  },
  { id: 12, label: '快適', description: '喜びに満ちた快適な人生を送る' },
  { id: 13, label: '誓約', description: '絶対に破れない約束や誓いを結ぶ' },
  { id: 14, label: '慈愛', description: '他者を心配して助ける' },
  { id: 15, label: '貢献', description: '世界の役に立つことをする' },
  { id: 16, label: '協調', description: '他者と強力して何かをする' },
  { id: 17, label: '礼儀', description: '他者に対して誠実で礼儀正しく接する' },
  { id: 18, label: '創造', description: '新しくて斬新なアイデアを生む' },
  { id: 19, label: '信頼', description: '信用があって頼れる人間になる' },
  { id: 20, label: '義務', description: '自分の義務と責任を果たす' },
  { id: 21, label: '調和', description: '周囲の環境と調和しながら生きる' },
  { id: 22, label: '興奮', description: 'スリルと刺激に満ちた人生を送る' },
  {
    id: 23,
    label: '貞節',
    description: 'パートナーにウソをつかず誠実に生きる',
  },
  { id: 24, label: '名声', description: '有名になって存在を認めれる' },
  { id: 25, label: '家族', description: '幸福で愛に満ちた家庭を作る' },
  { id: 26, label: '体力', description: '丈夫で強い身体を保つ' },
  { id: 27, label: '柔軟', description: '新たな環境にも簡単になじむ' },
  { id: 28, label: '許し', description: '他人を許しながら生きる' },
  { id: 29, label: '友情', description: '親密で助け合える友人を作る' },
  { id: 30, label: '愉楽', description: '遊んで楽しむこと' },
  { id: 31, label: '寛大', description: '自分の物を他人にあたえる' },
  { id: 32, label: '真実', description: '自分が正しいと思うとおりに行動する' },
  { id: 33, label: '信教', description: '自分を超えた存在の意思を考える' },
  { id: 34, label: '成長', description: '変化と成長を維持する' },
  { id: 35, label: '健康', description: '健やかで体調よく生きる' },
  { id: 36, label: '有益', description: '他人の役に立つこと' },
  { id: 37, label: '正直', description: 'ウソをつかず正直に生きる' },
  { id: 38, label: '希望', description: 'ポジティブで楽観的に生きる' },
  { id: 39, label: '謙遜', description: '地味で控えめに生きる' },
  { id: 40, label: '笑い', description: '人生や世界のユーモラスな側面を見る' },
  { id: 41, label: '独立', description: '他者に依存しないで生きる' },
  { id: 42, label: '勤勉', description: '自分の仕事に一生懸命取り組む' },
  { id: 43, label: '平安', description: '自分の内面の平和を維持する' },
  {
    id: 44,
    label: '親密',
    description: 'プライベートな体験を他人とシェアする',
  },
  { id: 45, label: '正義', description: 'すべての人を公平に扱う' },
  { id: 46, label: '知識', description: '価値ある知識を学ぶ、または生み出す' },
  { id: 47, label: '余暇', description: '自分の時間をリラックスして楽しむ' },
  { id: 48, label: '寵愛', description: '親しい人から愛される' },
  { id: 49, label: '愛慕', description: '誰かに愛をあたえる' },
  { id: 50, label: '熟達', description: 'いつもの仕事・作業に習熟する' },
  { id: 51, label: '現在', description: 'いまの瞬間に集中して生きる' },
  { id: 52, label: '適度', description: '過剰を避けてほどよいところを探す' },
  { id: 53, label: '単婚', description: '唯一の愛し合える相手を見つける' },
  { id: 54, label: '反抗', description: '権威やルールに疑問を持って挑む' },
  { id: 55, label: '配慮', description: '他人を心づかって世話すること' },
  { id: 56, label: '開放', description: '新たな体験、発想、選択肢に心を開く' },
  { id: 57, label: '秩序', description: '整理されて秩序のある人生を送る' },
  {
    id: 58,
    label: '情熱',
    description: 'なんらかの発想、活動、人々に深い感情を抱く',
  },
  { id: 59, label: '快楽', description: '良い気分になること' },
  { id: 60, label: '人気', description: '多くの人に好かれる' },
  { id: 61, label: '権力', description: '他人をコントロールする' },
  { id: 62, label: '目的', description: '人生の意味と方向性を定める' },
  { id: 63, label: '合理', description: '理性と論理に従う' },
  { id: 64, label: '現実', description: '現実的、実践的にふるまう' },
  { id: 65, label: '責任', description: '責任をもって行動する' },
  { id: 66, label: '危険', description: 'リスクを取ってチャンスを手に入れる' },
  { id: 67, label: '恋愛', description: '興奮して燃えるような恋をする' },
  { id: 68, label: '安全', description: '安心感を得る' },
  { id: 69, label: '受諾', description: 'ありのままの自分を受け入れる' },
  { id: 70, label: '自制', description: '自分の行動を自分でコントロールする' },
  { id: 71, label: '自尊', description: '自分に自信を持つ' },
  { id: 72, label: '自知', description: '自分について深い理解を持つ' },
  { id: 73, label: '献身', description: '誰かに奉仕する' },
  { id: 74, label: '性愛', description: '活動的で満足のいく性生活を送る' },
  { id: 75, label: '単純', description: 'シンプルでミニマルな暮らしをする' },
  {
    id: 76,
    label: '孤独',
    description: '他人から離れて１人でいられる時間と空間を持つ',
  },
  { id: 77, label: '精神', description: '精神的に成長し成熟する' },
  { id: 78, label: '安定', description: 'いつも一定して変化のない人生を送る' },
  { id: 79, label: '寛容', description: '自分と違う存在を尊重して受け入れる' },
  {
    id: 80,
    label: '伝統',
    description: '過去から受け継がれてきたパターンを尊重する',
  },
  { id: 81, label: '美徳', description: '道徳的に優れた生活を送る' },
  { id: 82, label: '富', description: 'たくさんお金を持っている' },
  { id: 83, label: '世界平和', description: '世界の平和を促進する為に働く' },
]
