name: Deploy to Firebase

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies of client
        run: yarn install --prefer-offline
      - name: Install Dependencies of server
        run: yarn install --prefer-offline
        working-directory: ./functions
      - name: Deploy to firebase
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./functions
